# Generated by Django 5.0.1 on 2024-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('empID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('companyCode', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('cost_center', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
