# Generated by Django 5.0.1 on 2024-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='approve',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='manager_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='adminApprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='managerApprove',
            field=models.BooleanField(default=False),
        ),
    ]
