# Generated by Django 5.0.1 on 2024-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_weeklyreport_submit_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='approve_date',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='reject_date',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='approve_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='reject_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
