# Generated by Django 5.0.1 on 2024-03-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('projectCode', models.CharField(max_length=100, unique=True)),
                ('projectSubCode', models.CharField(max_length=100, unique=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('addedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_added_by', to=settings.AUTH_USER_MODEL)),
                ('projectManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
