# Generated by Django 5.0.1 on 2024-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectSubCode',
            field=models.JSONField(default=list),
        ),
    ]
